{% set version = "2.6.1" %}

package:
  name: torch-geometric
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/torch-geometric/torch_geometric-{{ version }}.tar.gz
  sha256: 1f18f9d0fc4d2239d526221e4f22606a4a3895b5d965a9856d27610a3df662c6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
  run:
    - aiohttp
    - fsspec
    - jinja2
    - numpy
    - psutil
    - pyparsing
    - python >={{ python_min }}
    - pytorch
    - requests
    - tqdm

test:
  imports:
    - torch_geometric
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyg-team/pytorch_geometric
  summary: Graph Neural Network Library for PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
