schema_version: 1

context:
  version: "2.8.0.post1"

package:
  name: torch-geometric
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/torch-geometric/torch_geometric-${{ version }}.tar.gz
  sha256: 2c0c81666ec10f2132f6b4e0b6c57fc813f2c9f6b57599d7b7a799c614c22fbd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core
    - pip
    - python =${{ python_min }}
  run:
    - aiohttp
    - fsspec
    - jinja2
    - numpy
    - psutil
    - pyparsing
    - python >=${{ python_min }}
    - pytorch
    - requests
    - tqdm

tests:
  - python:
      imports:
        - torch_geometric
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: Graph Neural Network Library for PyTorch
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pyg-team/pytorch_geometric

extra:
  recipe-maintainers:
    - danielnachun
